### ISSUE TITLE
Make login/logout URL configurable

### ISSUE THREAD

**Issue by pka** [qwc-services/qwc-admin-gui#21]
Currently, `$TENANT_PREFIX/auth/login` is hardcoded for login redirects. We should also support other login URL's like `/intranet/ldap-auth/login`

**Comment by pka** [comment]
It's now `$TENANT_PREFIX/$AUTH_PATH/login` e.g. `/org1/auth/login`

**Comment by pka** [comment]
It's now `$TENANT_PREFIX/$AUTH_PATH/login` e.g. `/org1/auth/login`

**Comment by NullSeile** [comment]
We are having some trouble setting up this service using tenants. Our authentication service used by qwc2 is located in `http://<server-ip>/auth`. Are we supposed to move it to match `$TENANT_PREFIX/$AUTH_PATH/login`? Shouldn't we be able to set the complete url of the auth service in the configuration file?
