### ISSUE TITLE
Plugin themes : upload projects or files on server

### ISSUE THREAD

**Issue by benoitblanc** [qwc-services/qwc-admin-gui#26]
Hi @mwa @manisandro ,

I have discovered recently the `themes` plugin in qwc-admin-gui and it is a nice feature to edit themesConfig.

I was wondering if it would be great for the user to be able to upload new QGIS projects or files from his/her desktop to the server ?

I have started something which looks like this : 

![image](https://user-images.githubusercontent.com/8960009/130986381-a3db82ea-fbd3-4ef4-a68a-762533cd953f.png)

User can add or delete QGS projects or geospatial files in `qgs_resources_path` on server. After uploading files, he could add project to the app by creating a new theme in `Theme configuration` tab.

Please tell me if it could be interesting to add new projects this way. Also, if you have some remarks or ideas on what I started to develop, do not hesitate !

Thanks,
Benoît Blanc

**Comment by manisandro** [comment]
Looks interesting!
