### ISSUE TITLE
Themes plugin : No tiled option

### ISSUE THREAD

**Issue by cazitouni** [qwc-services/qwc-admin-gui#47]
There is no option for the tiled mode in the theme plugin for QWC admin despite the fact that the option exists if you write it mannually in the json config. (tiled : true)
It could be a great addition to add this option into the plugin.

**Comment by manisandro** [comment]
I'd be happy to review and merge a corresponding pull request - should be pretty straight forward to implement.

**Comment by manisandro** [comment]
Closed via #48.
