### ISSUE TITLE
Themes plugin not working 

### ISSUE THREAD

**Issue by w0pr** [qwc-services/qwc-admin-gui#64]
I'm using qwc-docker image sourcepole/qwc-admin-gui:v2023.05.12 and have added "themes" to the plugin array in tenantConfig.json, but it does not show up in admin GUI, the config_editor however does and is working fine. 

![image](https://github.com/qwc-services/qwc-admin-gui/assets/8257055/65c1a63f-df19-4f2f-af67-24284f3b4fcb)

This is the part of the tenantConfig.json:
![image](https://github.com/qwc-services/qwc-admin-gui/assets/8257055/47140e70-9d74-4207-bac1-bbe6fe21e8f8)

Any ideas?

**Comment by cazitouni** [comment]
Hello @w0pr,

If you use docker have you uncommented the lines under qwc-admin-gui part: 

```
      # required by themes plugin:
      # - ./volumes/config-in:/srv/qwc_service/config-in:rw
      # - ./volumes/qwc2:/qwc2
      # - ./volumes/qgs-resources:/qgs-resources
```
Also you may have wrong value if you use the default docker template it should be this I think : 

```
   "qgs_resources_path": "/qgs-resources",,
    "qwc2_path": "/qwc2",
    "ogc_service_url": "/ows"
```

**Comment by w0pr** [comment]
Yes, I did uncomment those line in docker-compose.yml.

I fixed paths in tenantConfig.jason according to your suggestion and it is now working! Thank you!
![image](https://github.com/qwc-services/qwc-admin-gui/assets/8257055/864754d8-9408-446b-aba6-a4774171537f)

The plugins documentation needs some work...currently struggling with alkis plugin still.

**Comment by tpo** [comment]
@w0pr

> The plugins documentation needs some work...currently struggling with alkis plugin still.

I guess patches welcome

**Comment by w0pr** [comment]
@tpo 
> > The plugins documentation needs some work...currently struggling with alkis plugin still.
> 
> I guess patches welcome

Correct. The problem is, I was missing the whole point of ALKIS plugin (README.md was copied from themes plugin)
I got it working after all and I can see that it might be of some use to selectively enable preconfigured ALKIS data connections, if alkis table is referenced in QGIS projects, but has no realltion to function of qgis-services at all.

**Comment by AlexanderVoloshok** [comment]
I faced the same problem with themes plugin not working. I reproduced all the steps below, but I noticed, that I have no /owc directory inside qwc-docker/volumes . How can I create it? does it have some content by default?

**Comment by tpo** [comment]
> I faced the same problem with themes plugin not working. I reproduced all the steps below, but I noticed, that I have no /owc directory inside qwc-docker/volumes . How can I create it? does it have some content by default?

you mean you were missing a `qwc-docker/volumes/qwc` directory and *not* a `qwc-docker/volumes/owc` directory, right?

**Comment by AlexanderVoloshok** [comment]
> "qgs_resources_path": "/qgs-resources",
>     "qwc2_path": "/qwc2",
>     "ogc_service_url": "/ows"

No, I meant this message. Here's `ogc_service_url`, which is equal to `/ows`. In `qwc-docker/volumes` directory I see `qgs-resources` and `/qwc2` folders, so I expect that there should be `/ows` too. But there's no such folder.
